AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  techfood-lambda

  Sample SAM Template for techfood-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
  Api:
    Auth:
      ApiKeyRequired: false

Resources:
  TechfoodLambdaAuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: techfood-lambda/
      Handler: auth.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        TechfoodLambda:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth.ts
  TechfoodLambdaSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: techfood-lambda/
      Handler: signup.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        TechfoodLambda:
          Type: Api
          Properties:
            Path: /signup
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/signup.ts
  TechfoodLambdaSigninFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: techfood-lambda/
      Handler: signin.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        TechfoodLambda:
          Type: Api
          Properties:
            Path: /signin
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/signin.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TechfoodLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/techfood-lambda/"
  TechfoodLambdaAuthFunction:
    Description: "Auth Lambda Function ARN"
    Value: !GetAtt TechfoodLambdaAuthFunction.Arn
  TechfoodLambdaAuthFunctionIamRole:
    Description: "Auth Lambda Function IAM Role"
    Value: !GetAtt TechfoodLambdaAuthFunctionRole.Arn
  TechfoodLambdaSignupFunction:
    Description: "Signup Lambda Function ARN"
    Value: !GetAtt TechfoodLambdaSignupFunction.Arn
  TechfoodLambdaSignupFunctionIamRole:
    Description: "Implicit IAM Role created for Signup function"
    Value: !GetAtt TechfoodLambdaSignupFunctionRole.Arn
  TechfoodLambdaSigninFunction:
    Description: "Signin Lambda Function ARN"
    Value: !GetAtt TechfoodLambdaSigninFunction.Arn
  TechfoodLambdaSigninFunctionIamRole:
    Description: "Implicit IAM Role created for Signin function"
    Value: !GetAtt TechfoodLambdaSigninFunctionRole.Arn
